ComApp/Models/ComAppDatabase.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComAppDatabaseEntities : DbContext
    {
        public ComAppDatabaseEntities()
            : base("name=ComAppDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComData> ComData { get; set; }
    }
}

ComApp/Models/ComAppDatabase.Designer.cs
// T4 code generation is enabled for model 'D:\Projects\ComApp\ComApp\Models\ComAppDatabase.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

ComApp/Models/ComAppDatabase.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

ComApp/Models/ComData.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComData
    {
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string PostanskiBroj { get; set; }
        public string Grad { get; set; }
        public string Telefon { get; set; }
    }
}

ComApp/Models/ComDataMeta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComApp.Models
{
    public partial class ComData
    {
        public ComData() { }

        public ComData(string ime, string prezime, string postanskiBroj, string grad, string telefon)
        {
            Ime = ime;
            Prezime = prezime;
            PostanskiBroj = postanskiBroj;
            Grad = grad;
            Telefon = telefon;
        }
    }
}

ComApp/Controllers/ComController.cs
using ComApp.DAL;
using ComApp.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ComApp.Controllers
{
    public class ComController : Controller
    {
        private DataContext context = new DataContext();

        public ActionResult Index()
        {
            return View(context.ComData());
        }

        public ActionResult Upload()
        {
            var data = context.Upload();
            TempData["data"] = data;
            return View("Index", data);
        }

        public ActionResult Save()
        {   
            if(TempData["data"] != null)
            {
                var data = context.Save((List<ComData>)TempData["data"]);
                return View("Index", data);
            }
            return View("Index", context.ComData());
        }
    }
}

ComApp/Views/Com/Index.cshtml
@model IEnumerable<ComApp.Models.ComData>

@{
    ViewBag.Title = "Index";
}
@{
    var rowColor = "bg-white";
}
<br />
<div class="jumbotron text-center">
    <h1>CompApp</h1>
</div>

<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostanskiBroj)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefon)
        </th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            if (!item.PostanskiBroj.All(char.IsDigit))
            {
                rowColor = "bg-danger";
            }

            <tr class="@rowColor">
                <td>
                    @Html.DisplayFor(modelItem => item.Ime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prezime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostanskiBroj)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefon)
                </td>
            </tr>
                rowColor = "bg-white";
        }
    }

</table>

<div class="container">
    <div class="row text-center">
        <div class="col-md-1 col-md-offset-5">
            @Html.ActionLink("Upload", "Upload", "Com", null, new { @class = "btn btn-info" })
        </div>
        <div class="col-md-1">
            @Html.ActionLink("Save", "Save", "Com", null, new { @class = "btn btn-success" })
        </div>
    </div>
</div>

ComApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ComApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ComApp</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>